/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinal;

import instancias.LlamarInstancias;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Mariano
 */
public class FrameInicio extends javax.swing.JFrame {

    /**
     * Creates new form FrameInicio
     */
    FondoInicio fondoInicio = new FondoInicio();//Creamos un nuevo fondo
    public FrameInicio() {
        this.setContentPane(fondoInicio);//Realizamos la pintada de nuestro fondo
        initComponents();//Iniciamos los componentes del Frame
        this.setLocationRelativeTo(null);//Centramos nuestro frame
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PasajerosBoton = new javax.swing.JButton();
        ManejoAeropuertoB = new javax.swing.JButton();
        TituloInicio = new javax.swing.JLabel();
        SalirDelSistema = new javax.swing.JButton();
        LogojLabel1 = new javax.swing.JLabel();
        LogojLabel2 = new javax.swing.JLabel();
        LogojLabel3 = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        PasajeroTexto = new javax.swing.JLabel();
        ManejarAeropuertoTexto = new javax.swing.JLabel();
        TituloInicioBienvenido = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio");

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PasajerosBoton.setBackground(new java.awt.Color(0, 204, 204));
        PasajerosBoton.setFont(new java.awt.Font("Engravers MT", 1, 24)); // NOI18N
        PasajerosBoton.setForeground(new java.awt.Color(0, 0, 0));
        PasajerosBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/PasajeroInicio.PNG"))); // NOI18N
        PasajerosBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasajerosBotonActionPerformed(evt);
            }
        });
        jPanel1.add(PasajerosBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 150, 170));

        ManejoAeropuertoB.setBackground(new java.awt.Color(0, 204, 204));
        ManejoAeropuertoB.setFont(new java.awt.Font("Engravers MT", 1, 24)); // NOI18N
        ManejoAeropuertoB.setForeground(new java.awt.Color(0, 0, 0));
        ManejoAeropuertoB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ManejarAeropuertoInicio.PNG"))); // NOI18N
        ManejoAeropuertoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManejoAeropuertoBActionPerformed(evt);
            }
        });
        jPanel1.add(ManejoAeropuertoB, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 300, 405, 191));

        TituloInicio.setFont(new java.awt.Font("Times New Roman", 1, 80)); // NOI18N
        TituloInicio.setForeground(new java.awt.Color(0, 0, 0));
        TituloInicio.setText("AeroBalamDevs");
        jPanel1.add(TituloInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, -1));

        SalirDelSistema.setBackground(new java.awt.Color(255, 0, 0));
        SalirDelSistema.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        SalirDelSistema.setForeground(new java.awt.Color(0, 0, 0));
        SalirDelSistema.setText("Salir");
        SalirDelSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirDelSistemaActionPerformed(evt);
            }
        });
        jPanel1.add(SalirDelSistema, new org.netbeans.lib.awtextra.AbsoluteConstraints(1107, 600, 158, 44));
        jPanel1.add(LogojLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 348, -1, -1));
        jPanel1.add(LogojLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(609, 300, -1, -1));
        jPanel1.add(LogojLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(619, 310, -1, -1));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logo.PNG"))); // NOI18N
        jPanel1.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, -1, -1));

        PasajeroTexto.setFont(new java.awt.Font("Engravers MT", 1, 24)); // NOI18N
        PasajeroTexto.setForeground(new java.awt.Color(0, 0, 0));
        PasajeroTexto.setText("Pasajeros");
        jPanel1.add(PasajeroTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, -1, -1));

        ManejarAeropuertoTexto.setFont(new java.awt.Font("Engravers MT", 1, 24)); // NOI18N
        ManejarAeropuertoTexto.setForeground(new java.awt.Color(0, 0, 0));
        ManejarAeropuertoTexto.setText("Manejo De Aeropuerto");
        ManejarAeropuertoTexto.setToolTipText("");
        jPanel1.add(ManejarAeropuertoTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 250, -1, -1));

        TituloInicioBienvenido.setFont(new java.awt.Font("Times New Roman", 1, 60)); // NOI18N
        TituloInicioBienvenido.setForeground(new java.awt.Color(0, 0, 0));
        TituloInicioBienvenido.setText("Bienvenido a la mejor empresa aeronáutica");
        jPanel1.add(TituloInicioBienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalirDelSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirDelSistemaActionPerformed
        JOptionPane.showMessageDialog(null, "Vuelve pronto, que tengas buen dia");
        System.exit(0);
    }//GEN-LAST:event_SalirDelSistemaActionPerformed

    private void PasajerosBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasajerosBotonActionPerformed
        LlamarInstancias.pasajeros();//Llamamos al frame pasajeros
        this.dispose();//Cerramos este frame
    }//GEN-LAST:event_PasajerosBotonActionPerformed

    private void ManejoAeropuertoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManejoAeropuertoBActionPerformed
        LlamarInstancias.manejoAeropuerto();//Llamamos al frame manejo aeropuerto
        this.dispose();//Cerramos este frame
    }//GEN-LAST:event_ManejoAeropuertoBActionPerformed
    class FondoInicio extends JPanel{//creamos una clase parametrica o generica extendiendo de JPanel
        private Image imagen;//establecemos que sea tipo imagen
        @Override//sobrescribimos la clase JPanel especificamente el metodo paint
        public void paint(Graphics g){ 
            imagen = new ImageIcon(getClass().getResource("/imagenes/FondoInicio.jpg")).getImage();//igualamos nuestra variable al fondo que queremos
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);//damos las dimensiones
            setOpaque(false);//Ponemos que el panel no sea visible
            super.paint(g);//llamos a la clase super para que cumpla con las funcionalidades del JPanel
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel LogojLabel1;
    private javax.swing.JLabel LogojLabel2;
    private javax.swing.JLabel LogojLabel3;
    private javax.swing.JLabel ManejarAeropuertoTexto;
    private javax.swing.JButton ManejoAeropuertoB;
    private javax.swing.JLabel PasajeroTexto;
    private javax.swing.JButton PasajerosBoton;
    private javax.swing.JButton SalirDelSistema;
    private javax.swing.JLabel TituloInicio;
    private javax.swing.JLabel TituloInicioBienvenido;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
