/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package instancias;

import controladorDatos.HiloControlRecomendacion;
import java.awt.Graphics;
import java.awt.Image;
import java.io.File;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import static instancias.FramePasajeros.c;
import static instancias.FrameVentaAsientos.frameVentaAsientos;
import static instancias.FrameVisualizarDistribucionAsientos.frameVisualizarDistribucionAsientos;
import java.awt.Toolkit;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import manejadorArchivosUser.Pasaporte;
import static proyectofinal.ProyectoFinal.c1;

/**
 *
 * @author Mariano
 */
public class FrameCompraBoletos extends javax.swing.JFrame {

    /**
     * Creates new form FrameCompraBoletos
     */
    
    FondoInicio fondoCompraBoletos = new FondoInicio();//Creamos un nuevo fondo
    public FrameCompraBoletos() {
        this.setContentPane(fondoCompraBoletos);//Realizamos la pintada de nuestro fondo
        initComponents();
        
        this.setLocationRelativeTo(null);//Centramos nuestro frame
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        SalirDelSistema = new javax.swing.JButton();
        RegresarMenu = new javax.swing.JButton();
        Logo = new javax.swing.JLabel();
        irCompraBoleto = new javax.swing.JButton();
        ciudadOrigen = new javax.swing.JComboBox<>();
        ciudadDestino = new javax.swing.JComboBox<>();
        cuidadDestinotext = new javax.swing.JLabel();
        ciudadOirgentext = new javax.swing.JLabel();
        FechaVueloField = new javax.swing.JFormattedTextField();
        fechaVuelotext = new javax.swing.JLabel();
        CantidadPasajeros = new javax.swing.JComboBox<>();
        cantidadPasajerostext = new javax.swing.JLabel();
        ciudadOirgentext1 = new javax.swing.JLabel();
        EntradaPasaporte = new javax.swing.JTextField();
        pasaporteTexto = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SalirDelSistema.setBackground(new java.awt.Color(255, 0, 0));
        SalirDelSistema.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        SalirDelSistema.setForeground(new java.awt.Color(0, 0, 0));
        SalirDelSistema.setText("Salir");
        SalirDelSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirDelSistemaActionPerformed(evt);
            }
        });
        jPanel1.add(SalirDelSistema, new org.netbeans.lib.awtextra.AbsoluteConstraints(1107, 600, 158, 44));

        RegresarMenu.setBackground(new java.awt.Color(255, 0, 0));
        RegresarMenu.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        RegresarMenu.setForeground(new java.awt.Color(0, 0, 0));
        RegresarMenu.setText("Regresar");
        RegresarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarMenuActionPerformed(evt);
            }
        });
        jPanel1.add(RegresarMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 600, 160, 44));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logo.PNG"))); // NOI18N
        jPanel1.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, -1, -1));

        irCompraBoleto.setBackground(new java.awt.Color(0, 204, 204));
        irCompraBoleto.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        irCompraBoleto.setForeground(new java.awt.Color(0, 0, 0));
        irCompraBoleto.setText("Ir a compra boleto");
        irCompraBoleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irCompraBoletoActionPerformed(evt);
            }
        });
        jPanel1.add(irCompraBoleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 480, -1, -1));

        ciudadOrigen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Afganistán", "Albania", "Alemania", "Andorra", "Angola", "Antigua y Barbuda", "Arabia Saudita", "Argelia", "Argentina", "Armenia", "Australia", "Austria", "Azerbaiyán", "Bahamas", "Bangladés", "Barbados", "Belice", "Benín", "Bielorrusia", "Birmania", "Bolivia", "Bosnia y Herzegovina", "Botsuana", "Brasil", "Brunéi", "Bulgaria", "Burkina Faso", "Burundi", "Bután", "Cabo Verde", "Camboya", "Camerún", "Canadá", "Catar", "Chad", "Chile", "China", "Chipre", "Ciudad del Vaticano", "Colombia", "Comoras", "Corea del Norte", "Corea del Sur", "Costa de Marfil", "Costa Rica", "Croacia", "Cuba", "Dinamarca", "Dominica", "Ecuador", "Egipto", "El Salvador", "Emiratos Árabes Unidos", "Eritrea", "Eslovaquia", "Eslovenia", "España", "Estados Unidos", "Estonia", "Etiopía", "Filipinas", "Finlandia", "Fiyi", "Francia", "Gabón", "Gambia", "Georgia", "Ghana", "Granada", "Grecia", "Guatemala", "Guyana", "Guinea", "Guinea ecuatorial", "Guinea-Bisáu", "Haití", "Honduras", "Hungría", "India", "Indonesia", "Irak", "Irán", "Irlanda", "Islandia", "Islas Marshall", "Islas Salomón", "Israel", "Italia", "Jamaica", "Japón", "ordania", "Kazajistán", "Kenia", "Kirguistán", "Kiribati", "Kuwait", "Laos", "Lesoto", "Letonia", "Líbano", "Liberia", "Libia", "Liechtenstein", "Lituania", "Luxemburgo", "Macedonia del Norte", "Madagascar", "Malasia", "Malaui", "Maldivas", "Malí", "Malta", "Marruecos", "Mauricio", "Mauritania", "México", "Micronesia", "Moldavia", "Mónaco", "Mongolia", "Montenegro", "Mozambique", "Namibia", "Nauru", "Nepal", "Nicaragua", "Níger", "Nigeria", "Noruega", "Nueva Zelanda", "Omán", "Países Bajos", "Pakistán", "Palaos", "Panamá", "Papúa Nueva Guinea", "Paraguay", "Perú", "Polonia", "Portugal", "Reino Unido", "República Centroafricana", "República Checa", "República del Congo", "República Democrática del Congo", "República Dominicana", "Ruanda", "Rumanía", "Rusia", "Samoa", "San Cristóbal y Nieves", "San Marino", "San Vicente y las Granadinas", "Santa Lucía", "Santo Tomé y Príncipe", "Senegal", "Serbia", "Seychelles", "Sierra Leona", "Singapur", "Siria", "Somalia", "Sri Lanka", "Suazilandia", "Sudáfrica", "Sudán", "Sudán del Sur", "Suecia", "Suiza", "Surinam", "Tailandia", "Tanzania", "Tayikistán", "Timor Oriental", "Togo", "Tonga", "Trinidad y Tobago", "Túnez", "Turkmenistán", "Turquía", "Tuvalu", "Ucrania", "Uganda", "Uruguay", "Uzbekistán", "Vanuatu", "Venezuela", "Vietnam", "Yemen", "Yibuti", "Zambia", "Zimbabue" }));
        jPanel1.add(ciudadOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 170, 160, -1));

        ciudadDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Afganistán", "Albania", "Alemania", "Andorra", "Angola", "Antigua y Barbuda", "Arabia Saudita", "Argelia", "Argentina", "Armenia", "Australia", "Austria", "Azerbaiyán", "Bahamas", "Bangladés", "Barbados", "Belice", "Benín", "Bielorrusia", "Birmania", "Bolivia", "Bosnia y Herzegovina", "Botsuana", "Brasil", "Brunéi", "Bulgaria", "Burkina Faso", "Burundi", "Bután", "Cabo Verde", "Camboya", "Camerún", "Canadá", "Catar", "Chad", "Chile", "China", "Chipre", "Ciudad del Vaticano", "Colombia", "Comoras", "Corea del Norte", "Corea del Sur", "Costa de Marfil", "Costa Rica", "Croacia", "Cuba", "Dinamarca", "Dominica", "Ecuador", "Egipto", "El Salvador", "Emiratos Árabes Unidos", "Eritrea", "Eslovaquia", "Eslovenia", "España", "Estados Unidos", "Estonia", "Etiopía", "Filipinas", "Finlandia", "Fiyi", "Francia", "Gabón", "Gambia", "Georgia", "Ghana", "Granada", "Grecia", "Guatemala", "Guyana", "Guinea", "Guinea ecuatorial", "Guinea-Bisáu", "Haití", "Honduras", "Hungría", "India", "Indonesia", "Irak", "Irán", "Irlanda", "Islandia", "Islas Marshall", "Islas Salomón", "Israel", "Italia", "Jamaica", "Japón", "ordania", "Kazajistán", "Kenia", "Kirguistán", "Kiribati", "Kuwait", "Laos", "Lesoto", "Letonia", "Líbano", "Liberia", "Libia", "Liechtenstein", "Lituania", "Luxemburgo", "Macedonia del Norte", "Madagascar", "Malasia", "Malaui", "Maldivas", "Malí", "Malta", "Marruecos", "Mauricio", "Mauritania", "México", "Micronesia", "Moldavia", "Mónaco", "Mongolia", "Montenegro", "Mozambique", "Namibia", "Nauru", "Nepal", "Nicaragua", "Níger", "Nigeria", "Noruega", "Nueva Zelanda", "Omán", "Países Bajos", "Pakistán", "Palaos", "Panamá", "Papúa Nueva Guinea", "Paraguay", "Perú", "Polonia", "Portugal", "Reino Unido", "República Centroafricana", "República Checa", "República del Congo", "República Democrática del Congo", "República Dominicana", "Ruanda", "Rumanía", "Rusia", "Samoa", "San Cristóbal y Nieves", "San Marino", "San Vicente y las Granadinas", "Santa Lucía", "Santo Tomé y Príncipe", "Senegal", "Serbia", "Seychelles", "Sierra Leona", "Singapur", "Siria", "Somalia", "Sri Lanka", "Suazilandia", "Sudáfrica", "Sudán", "Sudán del Sur", "Suecia", "Suiza", "Surinam", "Tailandia", "Tanzania", "Tayikistán", "Timor Oriental", "Togo", "Tonga", "Trinidad y Tobago", "Túnez", "Turkmenistán", "Turquía", "Tuvalu", "Ucrania", "Uganda", "Uruguay", "Uzbekistán", "Vanuatu", "Venezuela", "Vietnam", "Yemen", "Yibuti", "Zambia", "Zimbabue" }));
        jPanel1.add(ciudadDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 230, 160, -1));

        cuidadDestinotext.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        cuidadDestinotext.setForeground(new java.awt.Color(0, 0, 0));
        cuidadDestinotext.setText("Ciudad de destino");
        jPanel1.add(cuidadDestinotext, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, -1, -1));

        ciudadOirgentext.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        ciudadOirgentext.setForeground(new java.awt.Color(0, 0, 0));
        ciudadOirgentext.setText("Ciudad de origen");
        jPanel1.add(ciudadOirgentext, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, -1, -1));

        FechaVueloField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        jPanel1.add(FechaVueloField, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 370, 160, 20));

        fechaVuelotext.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        fechaVuelotext.setForeground(new java.awt.Color(0, 0, 0));
        fechaVuelotext.setText("FECHA DE VUELO");
        jPanel1.add(fechaVuelotext, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 370, -1, -1));

        CantidadPasajeros.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        jPanel1.add(CantidadPasajeros, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 300, -1, -1));

        cantidadPasajerostext.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        cantidadPasajerostext.setForeground(new java.awt.Color(0, 0, 0));
        cantidadPasajerostext.setText("Cantidad de pasajeros ");
        jPanel1.add(cantidadPasajerostext, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 310, -1, -1));

        ciudadOirgentext1.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        ciudadOirgentext1.setForeground(new java.awt.Color(0, 0, 0));
        ciudadOirgentext1.setText("datos para viajar");
        jPanel1.add(ciudadOirgentext1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, -1, -1));

        EntradaPasaporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntradaPasaporteActionPerformed(evt);
            }
        });
        EntradaPasaporte.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                EntradaPasaporteKeyTyped(evt);
            }
        });
        jPanel1.add(EntradaPasaporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 430, 150, -1));

        pasaporteTexto.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        pasaporteTexto.setForeground(new java.awt.Color(0, 0, 0));
        pasaporteTexto.setText("Pasaporte");
        jPanel1.add(pasaporteTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 430, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoMadera.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 450, 410));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalirDelSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirDelSistemaActionPerformed
        JOptionPane.showMessageDialog(null, "Vuelve pronto, que tengas buen dia");//Mensaje de despedida
        System.exit(0);//Cerramos el sistema
    }//GEN-LAST:event_SalirDelSistemaActionPerformed

    private void RegresarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarMenuActionPerformed
        LlamarInstancias.pasajeros();//Regresamos al menu opciones
        this.dispose();//Cerramos este frame
    }//GEN-LAST:event_RegresarMenuActionPerformed

    private void irCompraBoletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irCompraBoletoActionPerformed
        /*
        -Establecemos variables para ser tomadas en cuenta al viajar
        -El (String) nos sirve para castear el item y pasarlo a tipo string
        -la cantidad de pasajeros lo podemos convertir de string a int por eso lo definimos como string
         */
        String ciudadOrigenValor= (String)ciudadOrigen.getSelectedItem();
        String ciudadDestinoValor= (String)ciudadDestino.getSelectedItem();
        String cantidadPasajerosValor=(String)CantidadPasajeros.getSelectedItem();
        String pasaporte = EntradaPasaporte.getText();
        String fechaVueloValor=FechaVueloField.getText();
        c.setVerCantidadPasajeros(Integer.parseInt(cantidadPasajerosValor));
        c.setValidarPasaporte(pasaporte);
        if(fechaVueloValor.isEmpty()){
            JOptionPane.showMessageDialog(null, "No dejes casillas vacias");//Mensaje casilla vacia
        }else{
            //Verificamos si el pasaporte existe o no
            File fichero=new File("C:/Users/Maria/OneDrive/Documentos/NetBeansProjects/ProyectoFinal/datos/pasaportes/"+c.getValidarPasaporte()+".bin");
            if(fichero.exists()){
                try {
                    //creamos archivos para poder llamar nuestros datos de pasaporte
                    FileInputStream archivo = new FileInputStream("C:/Users/Maria/OneDrive/Documentos/NetBeansProjects/ProyectoFinal/datos/pasaportes/"+c.getValidarPasaporte()+".bin");
                    ObjectInputStream objeto = new ObjectInputStream(archivo);
                    FileInputStream archivos = new FileInputStream("C:/Users/Maria/OneDrive/Documentos/NetBeansProjects/ProyectoFinal/datos/pasaportes/"+c.getValidarPasaporte()+".bin");
                    ObjectInputStream objetos = new ObjectInputStream(archivos);
                    FileInputStream archivos1 = new FileInputStream("C:/Users/Maria/OneDrive/Documentos/NetBeansProjects/ProyectoFinal/datos/pasaportes/"+c.getValidarPasaporte()+".bin");
                    ObjectInputStream objetos1 = new ObjectInputStream(archivos1);
                    //definimos variables para almacenar valores
                    String pasaporteDefinido = ((Pasaporte)objeto.readObject()).getPasaporte();
                    String nombreDefinido = ((Pasaporte)objetos.readObject()).getNombres();
                    String ciudadOrigen = ((Pasaporte)objetos1.readObject()).getPaisActual();
                    if(pasaporte.equals(pasaporteDefinido)&&ciudadOrigen.equals(ciudadOrigenValor)){//Unicamente si los datos estan bien podra ingresar
                            if(c.getTomarColumnas()==0){
                                JOptionPane.showMessageDialog(null, "Solicita el vuelo al administrador, no disponible");//Mensaje
                            }else{
                                JOptionPane.showMessageDialog(null, "a comprar "+ c.getVerCantidadPasajeros()+" boletos se ha dicho "+nombreDefinido);//Mensaje de bienvenida
                                vaciarValoresCompraBoletos();   
                                frameVentaAsientos.setVisible(true); //vamos a venta asientos
                                HiloControlRecomendacion hC = new HiloControlRecomendacion();//creamos un hilo animacion
                                hC.start();//iniciamos hilo animacion
                                llenarReportes();
                                c.setCapacidadComprar(c.getVerCantidadPasajeros());
                                this.dispose();//Cerramos este frame
                            }
                        }else{
                            Toolkit.getDefaultToolkit().beep();//sonido de error
                            JOptionPane.showMessageDialog(null, "Datos incorrectos o no eres de la ciudad de origen indicada");//Mensaje datos incorrectos               
                        } 
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(FrameCompraBoletos.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(FrameCompraBoletos.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(FrameCompraBoletos.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }else{
                Toolkit.getDefaultToolkit().beep();//sonido de error
                JOptionPane.showMessageDialog(null, "No estas registrado");//Mensaje datos incorrectos 
            }
        }      
    }//GEN-LAST:event_irCompraBoletoActionPerformed

    private void EntradaPasaporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntradaPasaporteActionPerformed

    }//GEN-LAST:event_EntradaPasaporteActionPerformed

    private void EntradaPasaporteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EntradaPasaporteKeyTyped
        //Combinacion de que la tecla se presione y se suelte
        if(EntradaPasaporte.getText().length()>7){//restringimos que no puede escribir mas de 8 digitos
            evt.consume();//el evento no permite seguir escribiendo
            Toolkit.getDefaultToolkit().beep();//sonido de error
            JOptionPane.showMessageDialog(null, "El pasaporte unicamente tiene 8 digitos");//Mensaje condicional digitos pasaporte
        }
        char comprobarSiEsLetra = evt.getKeyChar();//Creamos variable tipo caracter para que no pueda escribir letras
        if(Character.isLetter(comprobarSiEsLetra)){//Comprobamos si el usuario escribe letras
            evt.consume();//el evento no permite seguir escribiendo
            Toolkit.getDefaultToolkit().beep();//sonido de error
            JOptionPane.showMessageDialog(null, "No puedes escribir letras, unicamente digitos");//Mensaje condicional no escribir letras
        }
    }//GEN-LAST:event_EntradaPasaporteKeyTyped
    class FondoInicio extends JPanel{//creamos una clase parametrica o generica extendiendo de JPanel
        private Image imagen;//establecemos que sea tipo imagen
        @Override//sobrescribimos la clase JPanel especificamente el metodo paint
        public void paint(Graphics g){ 
            imagen = new ImageIcon(getClass().getResource("/imagenes/FondoCompraBoletos.jpg")).getImage();//igualamos nuestra variable al fondo que queremos
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);//damos las dimensiones
            setOpaque(false);//Ponemos que el panel no sea visible
            super.paint(g);//llamos a la clase super para que cumpla con las funcionalidades del JPanel
        }
    }
    private void llenarReportes() throws IOException, ClassNotFoundException{
        try {
            FileInputStream archivo1 = new FileInputStream("C:/Users/Maria/OneDrive/Documentos/NetBeansProjects/ProyectoFinal/datos/pasaportes/"+c.getValidarPasaporte()+".bin");
            ObjectInputStream objeto1 = new ObjectInputStream(archivo1);
            FileInputStream archivo2 = new FileInputStream("C:/Users/Maria/OneDrive/Documentos/NetBeansProjects/ProyectoFinal/datos/pasaportes/"+c.getValidarPasaporte()+".bin");
            ObjectInputStream objeto2 = new ObjectInputStream(archivo2);
            FileInputStream archivo3 = new FileInputStream("C:/Users/Maria/OneDrive/Documentos/NetBeansProjects/ProyectoFinal/datos/pasaportes/"+c.getValidarPasaporte()+".bin");
            ObjectInputStream objeto3 = new ObjectInputStream(archivo3);
            String sexoViaja = ((Pasaporte)objeto1.readObject()).getSexo();
            String nacionalidadViaja = ((Pasaporte)objeto2.readObject()).getNacionalidad();
            String estadoCivilViaja = ((Pasaporte)objeto3.readObject()).getEstadoCivil();
            
            c1.setNacionalidadViaja(nacionalidadViaja);
            if(sexoViaja.equals("Hombre")){
                c1.setHombreViaja(c1.getHombreViaja()+1);
            }
            if(sexoViaja.equals("Mujer")){
                c1.setMujerViaja(c1.getMujerViaja()+1);
            }
            if(estadoCivilViaja.equals("Soltero")){
                c1.setSolteroViaja(c1.getSolteroViaja()+1);
            }
            if(estadoCivilViaja.equals("Casado")){
                c1.setCasadoViaja(c1.getCasadoViaja()+1);
            }
            
               
        } catch (FileNotFoundException ex) {
            Logger.getLogger(FrameCompraBoletos.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
        }
    }
    private void vaciarValoresCompraBoletos(){
        FechaVueloField.setText("");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CantidadPasajeros;
    private javax.swing.JTextField EntradaPasaporte;
    private javax.swing.JFormattedTextField FechaVueloField;
    private javax.swing.JLabel Logo;
    private javax.swing.JButton RegresarMenu;
    private javax.swing.JButton SalirDelSistema;
    private javax.swing.JLabel cantidadPasajerostext;
    private javax.swing.JComboBox<String> ciudadDestino;
    private javax.swing.JLabel ciudadOirgentext;
    private javax.swing.JLabel ciudadOirgentext1;
    private javax.swing.JComboBox<String> ciudadOrigen;
    private javax.swing.JLabel cuidadDestinotext;
    private javax.swing.JLabel fechaVuelotext;
    private javax.swing.JButton irCompraBoleto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel pasaporteTexto;
    // End of variables declaration//GEN-END:variables
}
