/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package instancias;

import java.awt.Graphics;
import java.awt.Image;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import static proyectofinal.ProyectoFinal.c1;

/**
 *
 * @author Mariano
 */
public class FrameGerenciaAerolinea extends javax.swing.JFrame {

    /**
     * Creates new form FrameGerenciaAerolinea
     */
    FondoInicio gerenciaAerolinea = new FondoInicio();//Creamos un nuevo fondo
    public static FrameGerenciaAerolinea frameGerenciaAerolinea;
    public static void iniciarGerencia(){
        frameGerenciaAerolinea=new FrameGerenciaAerolinea();
    }
    public static void visible(){
        frameGerenciaAerolinea.setVisible(true);
    }
    public FrameGerenciaAerolinea() {
        this.setContentPane(gerenciaAerolinea);//Realizamos la pintada de nuestro fondo
        initComponents();
        this.setLocationRelativeTo(null);//Centramos nuestro frame
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        SalirDelSistema = new javax.swing.JButton();
        RegresarMenu = new javax.swing.JButton();
        Logo = new javax.swing.JLabel();
        rutaConcurrida = new javax.swing.JButton();
        sucursales = new javax.swing.JButton();
        ganancias = new javax.swing.JButton();
        passaporteNegados = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        gerenciaReporte = new javax.swing.JTextArea();
        limpiarReportes = new javax.swing.JButton();
        exportador = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerencia de Aerolinea");

        jPanel1.setOpaque(false);

        SalirDelSistema.setBackground(new java.awt.Color(255, 0, 0));
        SalirDelSistema.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        SalirDelSistema.setForeground(new java.awt.Color(0, 0, 0));
        SalirDelSistema.setText("Salir");
        SalirDelSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirDelSistemaActionPerformed(evt);
            }
        });

        RegresarMenu.setBackground(new java.awt.Color(255, 0, 0));
        RegresarMenu.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        RegresarMenu.setForeground(new java.awt.Color(0, 0, 0));
        RegresarMenu.setText("Regresar");
        RegresarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarMenuActionPerformed(evt);
            }
        });

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logo.PNG"))); // NOI18N

        rutaConcurrida.setBackground(new java.awt.Color(255, 255, 0));
        rutaConcurrida.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        rutaConcurrida.setForeground(new java.awt.Color(0, 0, 0));
        rutaConcurrida.setText("rutas concurridas");
        rutaConcurrida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rutaConcurridaActionPerformed(evt);
            }
        });

        sucursales.setBackground(new java.awt.Color(255, 255, 0));
        sucursales.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        sucursales.setForeground(new java.awt.Color(0, 0, 0));
        sucursales.setText("sucursales");
        sucursales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sucursalesActionPerformed(evt);
            }
        });

        ganancias.setBackground(new java.awt.Color(255, 255, 0));
        ganancias.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        ganancias.setForeground(new java.awt.Color(0, 0, 0));
        ganancias.setText("Ganancias");
        ganancias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gananciasActionPerformed(evt);
            }
        });

        passaporteNegados.setBackground(new java.awt.Color(255, 255, 0));
        passaporteNegados.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        passaporteNegados.setForeground(new java.awt.Color(0, 0, 0));
        passaporteNegados.setText("pasaportes negados");
        passaporteNegados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passaporteNegadosActionPerformed(evt);
            }
        });

        gerenciaReporte.setColumns(20);
        gerenciaReporte.setRows(5);
        jScrollPane1.setViewportView(gerenciaReporte);

        limpiarReportes.setBackground(new java.awt.Color(204, 255, 51));
        limpiarReportes.setForeground(new java.awt.Color(0, 0, 0));
        limpiarReportes.setText("Limpiar reportes");
        limpiarReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarReportesActionPerformed(evt);
            }
        });

        exportador.setBackground(new java.awt.Color(204, 255, 51));
        exportador.setForeground(new java.awt.Color(0, 0, 0));
        exportador.setText("Exportador a .txt");
        exportador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportadorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Logo)
                .addGap(4, 4, 4)
                .addComponent(RegresarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(279, 279, 279)
                .addComponent(exportador)
                .addGap(35, 35, 35)
                .addComponent(limpiarReportes)
                .addGap(334, 334, 334)
                .addComponent(SalirDelSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 5, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(rutaConcurrida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(passaporteNegados)
                .addGap(103, 103, 103)
                .addComponent(ganancias)
                .addGap(91, 91, 91)
                .addComponent(sucursales)
                .addGap(67, 67, 67))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rutaConcurrida)
                    .addComponent(ganancias)
                    .addComponent(passaporteNegados)
                    .addComponent(sucursales))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 16, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Logo)
                            .addComponent(RegresarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SalirDelSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(limpiarReportes)
                            .addComponent(exportador))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalirDelSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirDelSistemaActionPerformed
        JOptionPane.showMessageDialog(null, "Vuelve pronto, que tengas buen dia");//Mensaje de despedida
        System.exit(0);//Cerramos el sistema
    }//GEN-LAST:event_SalirDelSistemaActionPerformed

    private void RegresarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarMenuActionPerformed
        LlamarInstancias.manejoAeropuerto();//Regresamos al manejo aeropuerto
        this.dispose();//Cerramos este frame
    }//GEN-LAST:event_RegresarMenuActionPerformed

    private void rutaConcurridaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rutaConcurridaActionPerformed
        gerenciaReporte.setText(gerenciaReporte.getText()+"\nRutas mas recorridas: ");
        
    }//GEN-LAST:event_rutaConcurridaActionPerformed

    private void sucursalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sucursalesActionPerformed
        gerenciaReporte.setText(gerenciaReporte.getText()+"\nPasaportes denegados: ");
    }//GEN-LAST:event_sucursalesActionPerformed

    private void gananciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gananciasActionPerformed
        gerenciaReporte.setText(gerenciaReporte.getText()+"\nGanancias Aeropuerto:  Q. "+c1.getDineroGanado()+"\n");
    }//GEN-LAST:event_gananciasActionPerformed

    private void passaporteNegadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passaporteNegadosActionPerformed
        gerenciaReporte.setText(gerenciaReporte.getText()+"\nReporteSucursales: ");
    }//GEN-LAST:event_passaporteNegadosActionPerformed

    private void limpiarReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarReportesActionPerformed
        gerenciaReporte.setText("");
    }//GEN-LAST:event_limpiarReportesActionPerformed

    private void exportadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportadorActionPerformed
        try {
            JFileChooser archivo = new JFileChooser(System.getProperty("C:/Users/Maria/OneDrive/Documentos/NetBeansProjects/ProyectoFinal/reportes"));
            archivo.showSaveDialog(this);
            if (archivo.getSelectedFile() != null) {
                try (FileWriter guardado = new FileWriter(archivo.getSelectedFile())) {
                    guardado.write(gerenciaReporte.getText());
                    JOptionPane.showMessageDialog(this, "El archivo fue guardado con éxito en la ruta establecida");
                }
            }
        } catch (IOException ex) {
            System.out.println("ex"+ex);
        }
    }//GEN-LAST:event_exportadorActionPerformed
    class FondoInicio extends JPanel{//creamos una clase parametrica o generica extendiendo de JPanel
        private Image imagen;//establecemos que sea tipo imagen
        @Override//sobrescribimos la clase JPanel especificamente el metodo paint
        public void paint(Graphics g){ 
            imagen = new ImageIcon(getClass().getResource("/imagenes/FondoManejoGerencia.jpg")).getImage();//igualamos nuestra variable al fondo que queremos
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);//damos las dimensiones
            setOpaque(false);//Ponemos que el panel no sea visible
            super.paint(g);//llamos a la clase super para que cumpla con las funcionalidades del JPanel
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JButton RegresarMenu;
    private javax.swing.JButton SalirDelSistema;
    private javax.swing.JButton exportador;
    private javax.swing.JButton ganancias;
    private javax.swing.JTextArea gerenciaReporte;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton limpiarReportes;
    private javax.swing.JButton passaporteNegados;
    private javax.swing.JButton rutaConcurrida;
    private javax.swing.JButton sucursales;
    // End of variables declaration//GEN-END:variables
}
