/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package instancias;

import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Mariano
 */
public class FrameManejoAeropuerto extends javax.swing.JFrame {

    /**
     * Creates new form FrameManejadorAeropuerto
     */
    FondoInicio fondoManejoAeropuerto = new FondoInicio();//Creamos un nuevo fondo
    public FrameManejoAeropuerto() {
        this.setContentPane(fondoManejoAeropuerto);//Realizamos la pintada de nuestro fondo
        initComponents();
        this.setLocationRelativeTo(null);//Centramos nuestro frame
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        RegresarMenu = new javax.swing.JButton();
        SalirDelSistema = new javax.swing.JButton();
        IniciarSesionAdmin = new javax.swing.JButton();
        ContraseñaAdmin = new javax.swing.JPasswordField();
        passwordAdmin = new javax.swing.JLabel();
        UsuarioAdministrador = new javax.swing.JTextField();
        UsuarioAdmin = new javax.swing.JLabel();
        LoginAdmin = new javax.swing.JLabel();
        TextAdmin = new javax.swing.JLabel();
        BarraBalnca = new javax.swing.JLabel();
        BarraBalnca1 = new javax.swing.JLabel();
        BarraBalnca2 = new javax.swing.JLabel();
        BarraBalnca3 = new javax.swing.JLabel();
        DepAdminTexto = new javax.swing.JLabel();
        IniciarSesionAdmin1 = new javax.swing.JButton();
        UsuarioAdministrador1 = new javax.swing.JTextField();
        passwordAdmin1 = new javax.swing.JLabel();
        BarraBalnca4 = new javax.swing.JLabel();
        ContraseñaAdmin1 = new javax.swing.JPasswordField();
        UsuarioAdmin1 = new javax.swing.JLabel();
        BarraBalnca5 = new javax.swing.JLabel();
        LoginAdmin1 = new javax.swing.JLabel();
        BarraBalnca6 = new javax.swing.JLabel();
        OpVuelos = new javax.swing.JLabel();
        TextAdmin1 = new javax.swing.JLabel();
        BarraBalnca7 = new javax.swing.JLabel();
        IniciarSesionAdmin2 = new javax.swing.JButton();
        UsuarioAdministrador2 = new javax.swing.JTextField();
        passwordAdmin2 = new javax.swing.JLabel();
        ContraseñaAdmin2 = new javax.swing.JPasswordField();
        UsuarioAdmin2 = new javax.swing.JLabel();
        BarraBalnca8 = new javax.swing.JLabel();
        BarraBalnca9 = new javax.swing.JLabel();
        LoginAdmin2 = new javax.swing.JLabel();
        BarraBalnca10 = new javax.swing.JLabel();
        TextAdmin2 = new javax.swing.JLabel();
        BarraBalnca11 = new javax.swing.JLabel();
        GerAerloinea = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manejo de Aeropuerto");

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logo.PNG"))); // NOI18N
        jPanel1.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, -1, -1));

        RegresarMenu.setBackground(new java.awt.Color(255, 0, 0));
        RegresarMenu.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        RegresarMenu.setForeground(new java.awt.Color(0, 0, 0));
        RegresarMenu.setText("Regresar al menu");
        RegresarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarMenuActionPerformed(evt);
            }
        });
        jPanel1.add(RegresarMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 600, 260, 44));

        SalirDelSistema.setBackground(new java.awt.Color(255, 0, 0));
        SalirDelSistema.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        SalirDelSistema.setForeground(new java.awt.Color(0, 0, 0));
        SalirDelSistema.setText("Salir");
        SalirDelSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirDelSistemaActionPerformed(evt);
            }
        });
        jPanel1.add(SalirDelSistema, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 600, 160, 44));

        IniciarSesionAdmin.setBackground(new java.awt.Color(0, 204, 204));
        IniciarSesionAdmin.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        IniciarSesionAdmin.setForeground(new java.awt.Color(0, 0, 0));
        IniciarSesionAdmin.setText("Iniciar Sesión");
        IniciarSesionAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarSesionAdminActionPerformed(evt);
            }
        });
        jPanel1.add(IniciarSesionAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, -1, -1));

        ContraseñaAdmin.setToolTipText("");
        ContraseñaAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContraseñaAdminActionPerformed(evt);
            }
        });
        ContraseñaAdmin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ContraseñaAdminKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ContraseñaAdminKeyTyped(evt);
            }
        });
        jPanel1.add(ContraseñaAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 150, -1));

        passwordAdmin.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        passwordAdmin.setForeground(new java.awt.Color(0, 0, 0));
        passwordAdmin.setText("Contraseña");
        jPanel1.add(passwordAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, -1));

        UsuarioAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioAdministradorActionPerformed(evt);
            }
        });
        UsuarioAdministrador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                UsuarioAdministradorKeyTyped(evt);
            }
        });
        jPanel1.add(UsuarioAdministrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 150, -1));

        UsuarioAdmin.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        UsuarioAdmin.setForeground(new java.awt.Color(0, 0, 0));
        UsuarioAdmin.setText("uSUARIO");
        jPanel1.add(UsuarioAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, -1));

        LoginAdmin.setFont(new java.awt.Font("Engravers MT", 1, 24)); // NOI18N
        LoginAdmin.setForeground(new java.awt.Color(0, 0, 0));
        LoginAdmin.setText("Login");
        jPanel1.add(LoginAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, -1, -1));

        TextAdmin.setBackground(new java.awt.Color(255, 255, 255));
        TextAdmin.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        TextAdmin.setForeground(new java.awt.Color(0, 0, 0));
        TextAdmin.setText("Departamento de Administración ");
        jPanel1.add(TextAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, 20));

        BarraBalnca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BarraBlanca.PNG"))); // NOI18N
        jPanel1.add(BarraBalnca, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 140, 30));

        BarraBalnca1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BarraBlanca.PNG"))); // NOI18N
        jPanel1.add(BarraBalnca1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 380, -1));

        BarraBalnca2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BarraBlanca.PNG"))); // NOI18N
        jPanel1.add(BarraBalnca2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 120, -1));

        BarraBalnca3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BarraBlanca.PNG"))); // NOI18N
        jPanel1.add(BarraBalnca3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 100, 30));

        DepAdminTexto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/DepAdmin.PNG"))); // NOI18N
        jPanel1.add(DepAdminTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 171, 370, 280));

        IniciarSesionAdmin1.setBackground(new java.awt.Color(0, 204, 204));
        IniciarSesionAdmin1.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        IniciarSesionAdmin1.setForeground(new java.awt.Color(0, 0, 0));
        IniciarSesionAdmin1.setText("Iniciar Sesión");
        IniciarSesionAdmin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarSesionAdmin1ActionPerformed(evt);
            }
        });
        jPanel1.add(IniciarSesionAdmin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 390, -1, -1));

        UsuarioAdministrador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioAdministrador1ActionPerformed(evt);
            }
        });
        UsuarioAdministrador1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                UsuarioAdministrador1KeyTyped(evt);
            }
        });
        jPanel1.add(UsuarioAdministrador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 260, 150, -1));

        passwordAdmin1.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        passwordAdmin1.setForeground(new java.awt.Color(0, 0, 0));
        passwordAdmin1.setText("Contraseña");
        jPanel1.add(passwordAdmin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, -1, -1));

        BarraBalnca4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BarraBlanca.PNG"))); // NOI18N
        jPanel1.add(BarraBalnca4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 320, 140, 30));

        ContraseñaAdmin1.setToolTipText("");
        ContraseñaAdmin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContraseñaAdmin1ActionPerformed(evt);
            }
        });
        ContraseñaAdmin1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ContraseñaAdmin1KeyTyped(evt);
            }
        });
        jPanel1.add(ContraseñaAdmin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 320, 150, -1));

        UsuarioAdmin1.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        UsuarioAdmin1.setForeground(new java.awt.Color(0, 0, 0));
        UsuarioAdmin1.setText("uSUARIO");
        jPanel1.add(UsuarioAdmin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, -1, -1));

        BarraBalnca5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BarraBlanca.PNG"))); // NOI18N
        jPanel1.add(BarraBalnca5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, 100, 30));

        LoginAdmin1.setFont(new java.awt.Font("Engravers MT", 1, 24)); // NOI18N
        LoginAdmin1.setForeground(new java.awt.Color(0, 0, 0));
        LoginAdmin1.setText("Login");
        jPanel1.add(LoginAdmin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, -1, -1));

        BarraBalnca6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BarraBlanca.PNG"))); // NOI18N
        jPanel1.add(BarraBalnca6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, 120, -1));

        OpVuelos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/OpVuelos.PNG"))); // NOI18N
        jPanel1.add(OpVuelos, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, 350, -1));

        TextAdmin1.setBackground(new java.awt.Color(255, 255, 255));
        TextAdmin1.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        TextAdmin1.setForeground(new java.awt.Color(0, 0, 0));
        TextAdmin1.setText("Operador de Vuelos");
        jPanel1.add(TextAdmin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, -1, 20));

        BarraBalnca7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BarraBlanca.PNG"))); // NOI18N
        jPanel1.add(BarraBalnca7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, 230, -1));

        IniciarSesionAdmin2.setBackground(new java.awt.Color(0, 204, 204));
        IniciarSesionAdmin2.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        IniciarSesionAdmin2.setForeground(new java.awt.Color(0, 0, 0));
        IniciarSesionAdmin2.setText("Iniciar Sesión");
        IniciarSesionAdmin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarSesionAdmin2ActionPerformed(evt);
            }
        });
        jPanel1.add(IniciarSesionAdmin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 380, -1, -1));

        UsuarioAdministrador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioAdministrador2ActionPerformed(evt);
            }
        });
        UsuarioAdministrador2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                UsuarioAdministrador2KeyTyped(evt);
            }
        });
        jPanel1.add(UsuarioAdministrador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 260, 150, -1));

        passwordAdmin2.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        passwordAdmin2.setForeground(new java.awt.Color(0, 0, 0));
        passwordAdmin2.setText("Contraseña");
        jPanel1.add(passwordAdmin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 330, -1, -1));

        ContraseñaAdmin2.setToolTipText("");
        ContraseñaAdmin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContraseñaAdmin2ActionPerformed(evt);
            }
        });
        ContraseñaAdmin2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ContraseñaAdmin2KeyTyped(evt);
            }
        });
        jPanel1.add(ContraseñaAdmin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 330, 150, -1));

        UsuarioAdmin2.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        UsuarioAdmin2.setForeground(new java.awt.Color(0, 0, 0));
        UsuarioAdmin2.setText("uSUARIO");
        jPanel1.add(UsuarioAdmin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 270, -1, -1));

        BarraBalnca8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BarraBlanca.PNG"))); // NOI18N
        jPanel1.add(BarraBalnca8, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 320, 140, 30));

        BarraBalnca9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BarraBlanca.PNG"))); // NOI18N
        jPanel1.add(BarraBalnca9, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 260, 100, 30));

        LoginAdmin2.setFont(new java.awt.Font("Engravers MT", 1, 24)); // NOI18N
        LoginAdmin2.setForeground(new java.awt.Color(0, 0, 0));
        LoginAdmin2.setText("Login");
        jPanel1.add(LoginAdmin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 180, -1, -1));

        BarraBalnca10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BarraBlanca.PNG"))); // NOI18N
        jPanel1.add(BarraBalnca10, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 180, 120, -1));

        TextAdmin2.setBackground(new java.awt.Color(255, 255, 255));
        TextAdmin2.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        TextAdmin2.setForeground(new java.awt.Color(0, 0, 0));
        TextAdmin2.setText("Gerencia de aerolinea");
        jPanel1.add(TextAdmin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 130, -1, 20));

        BarraBalnca11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BarraBlanca.PNG"))); // NOI18N
        jPanel1.add(BarraBalnca11, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 130, 250, -1));

        GerAerloinea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/GerAerolinea.PNG"))); // NOI18N
        jPanel1.add(GerAerloinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 170, -1, 270));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegresarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarMenuActionPerformed
        LlamarInstancias.inicioProyecto();//Regresamos al menu opciones
        this.dispose();//Cerramos este frame
    }//GEN-LAST:event_RegresarMenuActionPerformed

    private void SalirDelSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirDelSistemaActionPerformed
        JOptionPane.showMessageDialog(null, "Vuelve pronto, que tengas buen dia");//Mensaje de despedida
        System.exit(0);//Cerramos el sistema
    }//GEN-LAST:event_SalirDelSistemaActionPerformed

    private void IniciarSesionAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarSesionAdminActionPerformed
        //señalamos que seran una linea de caracteres establecida
        String usuario = UsuarioAdministrador.getText();
        String contraseñaAdmin = ContraseñaAdmin.getText();
        //Verificamos si una casilla esta vacia
        if(usuario.isEmpty()||contraseñaAdmin.isEmpty()){
            JOptionPane.showMessageDialog(null, "No dejes casillas vacias");//Mensaje casilla vacia
        }
        else{
            if(usuario.equals("Admin")&&contraseñaAdmin.equals("1234")){//Unicamente si los datos estan bien podra ingresar
                JOptionPane.showMessageDialog(null, "Bienvenido");//Mensaje de bienvenida
                LlamarInstancias.departamentoAdministracion();//Vamos a departamento de administracion
                this.dispose();//Cerramos este frame
            }else{
                Toolkit.getDefaultToolkit().beep();//sonido de error
                JOptionPane.showMessageDialog(null, "Datos incorrectos");//Mensaje datos incorrectos
            }
        }
    }//GEN-LAST:event_IniciarSesionAdminActionPerformed

    private void ContraseñaAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContraseñaAdminActionPerformed

    }//GEN-LAST:event_ContraseñaAdminActionPerformed

    private void ContraseñaAdminKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ContraseñaAdminKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_ContraseñaAdminKeyTyped

    private void UsuarioAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioAdministradorActionPerformed

    }//GEN-LAST:event_UsuarioAdministradorActionPerformed

    private void UsuarioAdministradorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UsuarioAdministradorKeyTyped
        //Combinacion de que la tecla se presione y se suelte
        if(UsuarioAdministrador.getText().length()>7){//restringimos que no puede escribir mas de 8 digitos
            evt.consume();//el evento no permite seguir escribiendo
            Toolkit.getDefaultToolkit().beep();//sonido de error
            JOptionPane.showMessageDialog(null, "El nombre no puede tener mas de 8 caracteres ");//Mensaje condicional caracteres
        }
        int comprobarSiEsNumero = evt.getKeyChar();//Creamos variable tipo caracter para que no pueda escribir numeros
        if(Character.isDigit(comprobarSiEsNumero)){//Comprobamos si el usuario escribe numeros
            evt.consume();//el evento no permite seguir escribiendo
            Toolkit.getDefaultToolkit().beep();//sonido de error
            JOptionPane.showMessageDialog(null, "No puedes escribir digitos, unicamente letras");//Mensaje condicional no escribir numeros
        }
    }//GEN-LAST:event_UsuarioAdministradorKeyTyped

    private void IniciarSesionAdmin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarSesionAdmin1ActionPerformed
        //señalamos que seran una linea de caracteres establecida
        String usuario1 = UsuarioAdministrador1.getText();
        String contraseñaAdmin1 = ContraseñaAdmin1.getText();
        //Verificamos si una casilla esta vacia
        if(usuario1.isEmpty()||contraseñaAdmin1.isEmpty()){
            JOptionPane.showMessageDialog(null, "No dejes casillas vacias");//Mensaje casilla vacia
        }
        else{
            if(usuario1.equals("Admin")&&contraseñaAdmin1.equals("1234")){//Unicamente si los datos estan bien podra ingresar
                JOptionPane.showMessageDialog(null, "Bienvenido");//Mensaje de bienvenida
                LlamarInstancias.operadorVuelos();//Vamos a operador vuelos
                this.dispose();//Cerramos este frame
            }else{
                Toolkit.getDefaultToolkit().beep();//sonido de error
                JOptionPane.showMessageDialog(null, "Datos incorrectos");//Mensaje datos incorrectos
            }
        }
    }//GEN-LAST:event_IniciarSesionAdmin1ActionPerformed

    private void UsuarioAdministrador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioAdministrador1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioAdministrador1ActionPerformed

    private void UsuarioAdministrador1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UsuarioAdministrador1KeyTyped
        //Combinacion de que la tecla se presione y se suelte
        if(UsuarioAdministrador1.getText().length()>7){//restringimos que no puede escribir mas de 8 digitos
            evt.consume();//el evento no permite seguir escribiendo
            Toolkit.getDefaultToolkit().beep();//sonido de error
            JOptionPane.showMessageDialog(null, "El nombre no puede tener mas de 8 caracteres ");//Mensaje condicional caracteres
        }
        int comprobarSiEsNumero = evt.getKeyChar();//Creamos variable tipo caracter para que no pueda escribir numeros
        if(Character.isDigit(comprobarSiEsNumero)){//Comprobamos si el usuario escribe numeros
            evt.consume();//el evento no permite seguir escribiendo
            Toolkit.getDefaultToolkit().beep();//sonido de error
            JOptionPane.showMessageDialog(null, "No puedes escribir digitos, unicamente letras");//Mensaje condicional no escribir numeros
        }
    }//GEN-LAST:event_UsuarioAdministrador1KeyTyped

    private void ContraseñaAdmin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContraseñaAdmin1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContraseñaAdmin1ActionPerformed

    private void ContraseñaAdmin1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ContraseñaAdmin1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_ContraseñaAdmin1KeyTyped

    private void IniciarSesionAdmin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarSesionAdmin2ActionPerformed
        //señalamos que seran una linea de caracteres establecida
        String usuario2 = UsuarioAdministrador2.getText();
        String contraseñaAdmin2 = ContraseñaAdmin2.getText();
        //Verificamos si una casilla esta vacia
        if(usuario2.isEmpty()||contraseñaAdmin2.isEmpty()){
            JOptionPane.showMessageDialog(null, "No dejes casillas vacias");//Mensaje casilla vacia
        }
        else{
            if(usuario2.equals("Admin")&&contraseñaAdmin2.equals("1234")){//Unicamente si los datos estan bien podra ingresar
                JOptionPane.showMessageDialog(null, "Bienvenido");//Mensaje de bienvenida
                LlamarInstancias.gerenciaAerolinea();//Vamos a gerencia aerolinea
                this.dispose();//Cerramos este frame
            }else{
                Toolkit.getDefaultToolkit().beep();//sonido de error
                JOptionPane.showMessageDialog(null, "Datos incorrectos");//Mensaje datos incorrectos
            }
        }
    }//GEN-LAST:event_IniciarSesionAdmin2ActionPerformed

    private void UsuarioAdministrador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioAdministrador2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioAdministrador2ActionPerformed

    private void UsuarioAdministrador2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UsuarioAdministrador2KeyTyped
        //Combinacion de que la tecla se presione y se suelte
        if(UsuarioAdministrador2.getText().length()>7){//restringimos que no puede escribir mas de 8 digitos
            evt.consume();//el evento no permite seguir escribiendo
            Toolkit.getDefaultToolkit().beep();//sonido de error
            JOptionPane.showMessageDialog(null, "El nombre no puede tener mas de 8 caracteres ");//Mensaje condicional caracteres
        }
        int comprobarSiEsNumero = evt.getKeyChar();//Creamos variable tipo caracter para que no pueda escribir numeros
        if(Character.isDigit(comprobarSiEsNumero)){//Comprobamos si el usuario escribe numeros
            evt.consume();//el evento no permite seguir escribiendo
            Toolkit.getDefaultToolkit().beep();//sonido de error
            JOptionPane.showMessageDialog(null, "No puedes escribir digitos, unicamente letras");//Mensaje condicional no escribir numeros
        }
    }//GEN-LAST:event_UsuarioAdministrador2KeyTyped

    private void ContraseñaAdmin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContraseñaAdmin2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContraseñaAdmin2ActionPerformed

    private void ContraseñaAdmin2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ContraseñaAdmin2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_ContraseñaAdmin2KeyTyped

    private void ContraseñaAdminKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ContraseñaAdminKeyPressed
        
    }//GEN-LAST:event_ContraseñaAdminKeyPressed
    class FondoInicio extends JPanel{//creamos una clase parametrica o generica extendiendo de JPanel
        private Image imagen;//establecemos que sea tipo imagen
        @Override//sobrescribimos la clase JPanel especificamente el metodo paint
        public void paint(Graphics g){ 
            imagen = new ImageIcon(getClass().getResource("/imagenes/ManejoAeropuertoFondo.jpg")).getImage();//igualamos nuestra variable al fondo que queremos
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);//damos las dimensiones
            setOpaque(false);//Ponemos que el panel no sea visible
            super.paint(g);//llamos a la clase super para que cumpla con las funcionalidades del JPanel
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BarraBalnca;
    private javax.swing.JLabel BarraBalnca1;
    private javax.swing.JLabel BarraBalnca10;
    private javax.swing.JLabel BarraBalnca11;
    private javax.swing.JLabel BarraBalnca2;
    private javax.swing.JLabel BarraBalnca3;
    private javax.swing.JLabel BarraBalnca4;
    private javax.swing.JLabel BarraBalnca5;
    private javax.swing.JLabel BarraBalnca6;
    private javax.swing.JLabel BarraBalnca7;
    private javax.swing.JLabel BarraBalnca8;
    private javax.swing.JLabel BarraBalnca9;
    private javax.swing.JPasswordField ContraseñaAdmin;
    private javax.swing.JPasswordField ContraseñaAdmin1;
    private javax.swing.JPasswordField ContraseñaAdmin2;
    private javax.swing.JLabel DepAdminTexto;
    private javax.swing.JLabel GerAerloinea;
    private javax.swing.JButton IniciarSesionAdmin;
    private javax.swing.JButton IniciarSesionAdmin1;
    private javax.swing.JButton IniciarSesionAdmin2;
    private javax.swing.JLabel LoginAdmin;
    private javax.swing.JLabel LoginAdmin1;
    private javax.swing.JLabel LoginAdmin2;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel OpVuelos;
    private javax.swing.JButton RegresarMenu;
    private javax.swing.JButton SalirDelSistema;
    private javax.swing.JLabel TextAdmin;
    private javax.swing.JLabel TextAdmin1;
    private javax.swing.JLabel TextAdmin2;
    private javax.swing.JLabel UsuarioAdmin;
    private javax.swing.JLabel UsuarioAdmin1;
    private javax.swing.JLabel UsuarioAdmin2;
    private javax.swing.JTextField UsuarioAdministrador;
    private javax.swing.JTextField UsuarioAdministrador1;
    private javax.swing.JTextField UsuarioAdministrador2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel passwordAdmin;
    private javax.swing.JLabel passwordAdmin1;
    private javax.swing.JLabel passwordAdmin2;
    // End of variables declaration//GEN-END:variables
}
